export const itemList = [
  { text: 'Znajdź fotografa', checked: false },
  { text: 'Zarezerwuj miejsce na ślub', checked: false },
  { text: 'Wybierz suknię ślubną', checked: false },
  { text: 'Wyślij zaproszenia na ślub', checked: false },
  { text: 'Zatrudnij wedding plannera', checked: false },
  { text: 'Zorganizuj catering', checked: false },
  { text: 'Zaplanuj degustację tortu', checked: false },
  { text: 'Zaplanuj ceremonię ślubną', checked: false },
  { text: 'Wybierz drużbów i druhny', checked: false },
  { text: 'Zorganizuj transport na dzień ślubu', checked: false },
  { text: 'Zatwierdź listę gości', checked: false },
  { text: 'Przygotuj playlistę lub zatrudnij DJ-a', checked: false },
  { text: 'Wybierz kompozycje kwiatowe', checked: false },
  { text: 'Kup obrączki', checked: false },
  { text: 'Stwórz plan rozmieszczenia gości', checked: false },
  { text: 'Umów próby fryzury i makijażu', checked: false },
  { text: 'Potwierdź obecność urzędnika ślubnego', checked: false },
  { text: 'Zaplanuj podróż poślubną', checked: false },
  { text: 'Zatwierdź harmonogram dnia ślubu', checked: false },
];
